# Generated by Django 3.1.1 on 2020-09-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200930_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHit',
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
