# Generated by Django 3.1.1 on 2020-11-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Слаг'),
        ),
    ]
