# Generated by Django 3.1.1 on 2020-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20201104_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'slug')},
        ),
    ]
