# Generated by Django 3.1.1 on 2020-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=150, unique=True, verbose_name='Слаг категорий'),
            preserve_default=False,
        ),
    ]
