# Generated by Django 3.1.1 on 2020-11-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='url',
        ),
    ]
