# Generated by Django 3.1.1 on 2020-11-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20201109_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
    ]
