# Generated by Django 3.1.1 on 2020-11-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20201110_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='photo',
            new_name='photo_category',
        ),
    ]
