# Generated by Django 3.1.1 on 2020-12-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20201110_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email пользователя')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок отзыва')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_add'],
            },
        ),
    ]
