# Generated by Django 3.1.1 on 2020-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20201218_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок гороскопа')),
                ('content', models.TextField(verbose_name='Гороскоп')),
                ('image', models.ImageField(blank=True, upload_to='photos_horosсope/%Y/%m/%d/', verbose_name='Картинка гороскопа')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг гороскопа')),
            ],
            options={
                'verbose_name': 'Гороскоп',
                'verbose_name_plural': 'Гороскопы',
                'ordering': ['-title'],
            },
        ),
    ]
