# Generated by Django 3.1.1 on 2020-12-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_horoscope_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='content',
            field=models.TextField(verbose_name='Текст гороскопа'),
        ),
    ]
