# Generated by Django 3.1.1 on 2020-12-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20201223_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscope',
            old_name='image',
            new_name='photo',
        ),
    ]
