# Generated by Django 3.1.1 on 2020-12-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_auto_20201223_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_horoscopes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='horoscopes_news', to='news.categoryhoroscopes', verbose_name='Месяц'),
            preserve_default=False,
        ),
    ]
