# Generated by Django 3.1.1 on 2020-12-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_news_category_horoscopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category_horoscopes',
        ),
        migrations.AddField(
            model_name='horoscope',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.news', verbose_name='Статьи'),
            preserve_default=False,
        ),
    ]
