# Generated by Django 3.1.5 on 2021-05-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание категории'),
        ),
    ]
