# Generated by Django 3.1.5 on 2021-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_auto_20210528_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.TextField(blank=True, verbose_name='Фрейм'),
        ),
    ]
